project:
  type: website
  output-dir: docs
  render:
    - "notebooks/oneday_predictor.qmd"
    - "notebooks/team_assessor.qmd"
    - "notebooks/backtesting.qmd"

jupyter: julia-1.12

website:
  title: "Velogames"
  sidebar:
    style: "docked"
    contents:
      - href: notebooks/oneday_predictor.qmd
        text: "One-day predictor"
      - href: notebooks/team_assessor.qmd
        text: "Team assessor"
      - href: notebooks/backtesting.qmd
        text: "Backtesting"

format:
  html:
    theme: flatly
    code-fold: true
    code-summary: "Show the code"
    toc: true
    toc_float: true

fig-cap-location: top
tbl-cap-location: top
fig-format: svg
link-external-icon: true

execute:
  echo: false
  warning: false
  cache: false
  freeze: auto

date-format: long
