---
title: "Historical analysis"
subtitle: "Gent-Wevelgem 2024"
---

Looking back on the race, what's the best team you could have picked? And what's the cheapest team you could have picked that would have beaten the best DPCC team?

```{julia}
using Velogames, DataFrames, HiGHS, JuMP, MarkdownTables

riderseriesurl = "https://www.velogames.com/sixes-superclasico/2024/riders.php"
riderraceurl = "https://www.velogames.com/sixes-superclasico/2024/ridescore.php?ga=13&st=6"
racehash = "#GentWevelgem"
bestteamscore = 1251;
```

# Best team you could have picked

```{julia}
#| output: false

# get the rider data
ridervgpost = getvgriders(riderseriesurl)
# ridervgpost = ridervgpost[ridervgpost.startlist.==racehash, :]

# this will only be needed for individual rounds of a longer series
riderracepoints = getvgracepoints(riderraceurl)

# join the datasets on riderkey
allriderdata = leftjoin(riderracepoints, ridervgpost, on=:riderkey, makeunique=true)
allriderdata = coalesce.(allriderdata, 0)
allriderdata.scoreperpoint = allriderdata.score ./ allriderdata.cost

# get rid of pipes in the team names to make the markdown table look better
allriderdata.team = replace.(allriderdata.team, r"\|" => "-")

modelpost = JuMP.Model(HiGHS.Optimizer)
JuMP.set_silent(modelpost)
JuMP.@variable(modelpost, x[allriderdata.rider], Bin)
# this will variously be points or scores depending whether it's a race or series
JuMP.@objective(modelpost, Max, allriderdata.score' * x) # maximise the total score. 
JuMP.@constraint(modelpost, allriderdata.cost' * x <= 100) # cost must be <= 100
JuMP.@constraint(modelpost, sum(x) == 6) # exactly 6 riders must be chosen
# @constraint(modelpost, ridervgpost.allrounder' * x >= 2) # at least 2 must be all rounders
# @constraint(modelpost, ridervgpost.sprinter' * x >= 1) # at least 1 must be a sprinter
# @constraint(modelpost, ridervgpost.climber' * x >= 2) # at least 2 must be climbers
# @constraint(modelpost, ridervgpost.unclassed' * x >= 3) # at least 3 must be unclassed
JuMP.optimize!(modelpost)
modelpostresults = JuMP.value.(x)

allriderdata.chosen = modelpostresults.data .> 0.5
chosenteampost = filter(row -> row.chosen, allriderdata)
```

With the benefit of hindsight, the best team you could have picked scored `{julia} chosenteampost.score |> sum` points and cost `{julia} chosenteampost.cost |> sum` points:

```{julia}
displaytable1 = rename(chosenteampost, :rider => :Rider, :team => :Team, :cost => :Cost, :score => :Score)
markdown_table(displaytable1[:, [:Rider, :Team, :Cost, :Score]])
```

# Cheapest team that would have beaten the best DPCC team

```{julia}
#| output: false

modelpost2 = JuMP.Model(HiGHS.Optimizer)
JuMP.set_silent(modelpost2)
JuMP.@variable(modelpost2, x[allriderdata.rider], Bin)
JuMP.@objective(modelpost2, Min, allriderdata.cost' * x) # maximise the total score
JuMP.@constraint(modelpost2, allriderdata.score' * x >= bestteamscore) # cost must be <= 100
JuMP.@constraint(modelpost2, sum(x) == 6) # exactly 9 riders must be chosen
# @constraint(modelpost2, allriderdata.allrounder' * x >= 2) # at least 2 must be all rounders
# @constraint(modelpost2, allriderdata.sprinter' * x >= 1) # at least 1 must be a sprinter
# @constraint(modelpost2, allriderdata.climber' * x >= 2) # at least 2 must be climbers
# @constraint(modelpost2, allriderdata.unclassed' * x >= 3) # at least 3 must be unclassed
JuMP.optimize!(modelpost2)
modelpost2results = JuMP.value.(x)

allriderdata.chosen2 = modelpost2results.data .> 0.5
chosen2teampost = filter(row -> row.chosen2, allriderdata)
```

The best team picked by a DPCC league member was Mark Readiot's, which scored `{julia} bestteamscore` points. The cheapest team that would have beaten that scored `{julia} chosen2teampost.score |> sum` points and cost `{julia} chosen2teampost.cost |> sum` points:

```{julia}
displaytable2 = rename(chosen2teampost, :rider => :Rider, :team => :Team, :cost => :Cost, :score => :Score)
markdown_table(displaytable2[:, [:Rider, :Team, :Cost, :Score]])
```

# Rider value

## Top picks

The highest value riders are the ones who scored the most points per credit cost:

```{julia}
# calculate points per cost
allriderdata.value = allriderdata.score ./ allriderdata.cost
# sort by ppc
sort!(allriderdata, :value, rev=true)
# select the top 20 riders an display in a table
displaytable3 = rename(allriderdata, :rider => :Rider, :team => :Team, :cost => :Cost, :score => :Score, :value => :Value)
displaytable3[!, :Value] = round.(displaytable3[!, :Value], digits=1)
displaytable3[!, :Rank] = 1:nrow(displaytable3)
displaytable3 = displaytable3[:, [:Rank, :Rider, :Team, :Cost, :Score, :Value]]
markdown_table(displaytable3[1:20, :])
```

## Worst picks

**Not available for this race for boring data reasons. Expect it back in future.**

<!-- The most expensive 15 riders who scored nil points:

```{julia}
# select the 15 riders with the highest cost who scored zero
zero_score_riders = filter(row -> row[:points] == 0, allriderdata)
sorted_riders = sort(zero_score_riders, :cost, rev=true)
top_15_riders = sorted_riders[1:15, :]
markdown_table(top_15_riders[end-14:end, [:rider, :team, :cost, :score, :value]])
``` -->
