project:
  type: website
  output-dir: docs

jupyter: julia-1.12

website:
  title: "Velogames: race reports"
  navbar:
    left:
      - text: Home
        href: index.qmd

format:
  html:
    theme: lux
    toc: true

fig-cap-location: top
tbl-cap-location: top
fig-format: svg
link-external-icon: true

execute:
  echo: false
  warning: false
  freeze: auto

date-format: long
